# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
    push:
        branches: [ "dev", "stage", "master", "main" ]
    pull_request: # Trigger on pull requests to any branch

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: '18'
                    cache: 'npm'

            -   name: Install dependencies
                run: npm install

            -   name: Install playwright
                run: npx playwright install --with-deps

            -   name: Run Spotless/Linter check
                run: npm run lint-ci
                continue-on-error: false

            -   name: Run tests
                run: npm run test
                if: success()
